services:
  api:
    container_name: codechat_api
    image: ghcr.io/ai-chat-os/codechat:v2
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8084:8084"
    volumes:
      - instances_connecteds:/codechat/instances
    environment:
      SERVER_PORT: 8084
      SESSION_SECRET: W0NvZGVDaGF0XTpbU2Vzc

      LOG_LEVEL: DEBUG #|ERROR|WARN|INFO||LOG|VERBOSE|DARK
      LOG_COLOR: true

      DATABASE_ENABLED: true
      DATABASE_URL: "postgres://codechat_user:f8Vi6XGgHnBkGj2qMTBm3k4XQGC3yBWE2@postgres_server:5432/codechat?schema: public"
      DATABASE_SYNC_MESSAGES: true
      DATABASE_SAVE_DATA_NEW_MESSAGE: true
      DATABASE_SAVE_MESSAGE_UPDATE: true
      DATABASE_SAVE_DATA_CONTACTS: true
      DATABASE_SAVE_DATA_CHATS: true

      GLOBAL_WEBHOOK_URL: url
      GLOBAL_WEBHOOK_ENABLED: false

      INSTANCE_EXPIRATION_TIME: false

      CONFIG_SESSION_PHONE_CLIENT: CodeChat_V1
      CONFIG_SESSION_PHONE_NAME: Chrome

      WA_VERSION: "[ 2, 3000, 1015901307 ]"

      QRCODE_LIMIT: 10
      QRCODE_EXPIRATION_TIME: 60
      QRCODE_LIGHT_COLOR: '#ffffff'
      QRCODE_DARK_COLOR: '#198754'

      CONNECTION_TIMEOUT: 300

      AUTHENTICATION_GLOBAL_AUTH_TOKEN: zYzP7ocstxh3SJ23D4FZTCu4ehnM8v4hu
      AUTHENTICATION_JWT_EXPIRES_IN: 0
      AUTHENTICATION_JWT_SECRET: 3RFYiiRmvNiokSBrLZzx

      PROVIDER_ENABLED: false
      PROVIDER_HOST: 127.0.0.1
      PROVIDER_PORT: 5656
      PROVIDER_PREFIX: codechat


      BASE_URL:

      # S3_ENABLED: false
      # S3_ACCESS_KEY: [ACCESS_KEY]
      # S3_SECRET_KEY: [SECRET_KEY]
      # S3_BUCKET: [BUCKET]
      # S3_PORT: 9000
      # S3_ENDPOINT: [ENDPOINT]
      # S3_USE_SSL: false
    networks:
      - db
      - public_network

  postgres_server:
    image: postgres:16
    container_name: postgres_server
    environment:
      POSTGRES_DB: codechat
      POSTGRES_USER: codechat_user
      POSTGRES_PASSWORD: "f8Vi6XGgHnBkGj2qMTBm3k4XQGC3yBWE2"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db
      - public_network

networks:
  db:
  public_network:

volumes:
  instances_connecteds:
  postgres_data:

